name = "aster"
compatibility_date = "2023-01-01"
main = "src/index.ts"

workers_dev = false # INSECURE, DO NOT ENABLE
route = { pattern = "cdn.www1.talkintummies.com", custom_domain = true } # CHANGEME

[site]
bucket = "./assets"

[vars]
PUBLIC_BUCKET_URL = "pub-72fc423b323b4dde81a42e8d5ecd24a6.r2.dev"
R2_BUCKET_NAME = "aster-test" # CHANGEME
CF_ACCOUNT_ID = "de47a12f1c8bb641a43895eca94e6290" # CHANGEME

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "aster-test" # CHANGEME
preview_bucket_name = "aster-test" # CHANGEME (optional, for development)
